# This file was generated by GoReleaser. DO NOT EDIT.
cask "ledger" do
  name "ledger"
  desc "Spot Canvas ledger CLI — query accounts, positions, trades, and import historic data"
  homepage "https://github.com/Spot-Canvas/ledger"
  version "0.1.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ledger"

  on_macos do
    on_intel do
      url "https://github.com/Spot-Canvas/ledger/releases/download/v#{version}/ledger_darwin_amd64.tar.gz"
      sha256 "88e1bf19d1e7899d43a6b07eff969c7d6af1e04c8b30b71d3f151f76411ffb82"
    end
    on_arm do
      url "https://github.com/Spot-Canvas/ledger/releases/download/v#{version}/ledger_darwin_arm64.tar.gz"
      sha256 "9065867569a7e2ea0de08c5d73f6a064808a0787a89042f5c8c020deefc67a2d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Spot-Canvas/ledger/releases/download/v#{version}/ledger_linux_amd64.tar.gz"
      sha256 "0a4b42c325c4cbb6c93125e8e221f476ee5c605da428bc61956c0d55a92c3340"
    end
  end

  # No zap stanza required
end
