# This file was generated by GoReleaser. DO NOT EDIT.
cask "ledger" do
  name "ledger"
  desc "Spot Canvas ledger CLI — query accounts, positions, trades, and import historic data"
  homepage "https://github.com/Spot-Canvas/ledger"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ledger"

  on_macos do
    on_intel do
      url "https://github.com/Spot-Canvas/ledger/releases/download/v#{version}/ledger_darwin_amd64.tar.gz"
      sha256 "6ffd3a39ddc05bafaa84e47eb2a4ec2dd904c2a4084e78a57b138b86f42a1a3d"
    end
    on_arm do
      url "https://github.com/Spot-Canvas/ledger/releases/download/v#{version}/ledger_darwin_arm64.tar.gz"
      sha256 "369fc763ef7ac1bc3682148dfba7548ec1e915db273190d25b7157532e0a0002"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Spot-Canvas/ledger/releases/download/v#{version}/ledger_linux_amd64.tar.gz"
      sha256 "fdace7ea0499e8728d1b0385a8f2d9dc791801abbaab10ca5aae23e9af674aba"
    end
  end

  # No zap stanza required
end
