# This file was generated by GoReleaser. DO NOT EDIT.
cask "trader" do
  version "0.9.8"

  on_macos do
    on_intel do
      url "https://github.com/Signal-ngn/trader/releases/download/v#{version}/trader_darwin_amd64.tar.gz"
      sha256 "5b765eb6674b6288f8b5e720303bb3c0e6bbd9da0127cf338ac0c4c5a5e84b68"
    end
    on_arm do
      url "https://github.com/Signal-ngn/trader/releases/download/v#{version}/trader_darwin_arm64.tar.gz"
      sha256 "a30fb2c4156d79f8c243d4d3118435f9977e272a54832939234b80a5fed92c4f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Signal-ngn/trader/releases/download/v#{version}/trader_linux_amd64.tar.gz"
      sha256 "243c79c8f614729260d01cb14bdb64d45543bd48a1fb6c45a0aeada0dc158e15"
    end
  end

  name "trader"
  desc "Signal Ngn trader CLI — query accounts, positions, trades, and manage live exchange orders"
  homepage "https://github.com/Signal-ngn/trader"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "trader"

  # No zap stanza required

end
