# This file was generated by GoReleaser. DO NOT EDIT.
cask "trader" do
  name "trader"
  desc "Signal Ngn trader CLI — query accounts, positions, trades, and manage live exchange orders"
  homepage "https://github.com/Signal-ngn/trader"
  version "0.9.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "trader"

  on_macos do
    on_intel do
      url "https://github.com/Signal-ngn/trader/releases/download/v#{version}/trader_darwin_amd64.tar.gz"
      sha256 "ca42fcbed6c5d73152f8525cdc6787ff9646aca33f840ce9d97c54cd7be5ced5"
    end
    on_arm do
      url "https://github.com/Signal-ngn/trader/releases/download/v#{version}/trader_darwin_arm64.tar.gz"
      sha256 "693f81d78b1c9f8393fde58693dde4f08ee0c4cdc7491a7bde3e501a2cbd9395"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Signal-ngn/trader/releases/download/v#{version}/trader_linux_amd64.tar.gz"
      sha256 "3e659447806aabcb529d41c0cf3f238cbb944ef26049882fc60ac3cddc8cff10"
    end
  end

  # No zap stanza required
end
